import { NextRequest, NextResponse } from 'next/server';
import { getOperatorSession } from '@/lib/auth/session';
import { kvGet, kvSet } from '@/lib/kv/store';
import { getServiceAuthError } from '@/lib/security/serviceAuth';
import { writeToSubstrate, type SubstrateEntry } from '@/lib/substrate/client';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const RECEIPT_WRITE_TTL_SECONDS = 60 * 60 * 24 * 90;

type LedgerExecuteBody = {
  action_id?: string;
  operator_ack?: boolean;
  dry_run?: boolean;
  receipts?: Record<string, unknown>;
};

type ReceiptBundlePayload = {
  ok?: boolean;
  bundle?: {
    action_id: string;
    action: string;
    lead_agent: string;
    supporting_agents: string[];
    priority: string;
    executable: boolean;
    payload_hash: string;
    quorum_hash: string;
    receipt_hash: string;
    rationale: string;
    created_at: string;
  };
  ledger_preview?: {
    title: string;
    summary: string;
    confidenceTier?: number;
    status?: string;
    tags?: string[];
  };
  blocked_by?: string[];
};

type LedgerExecutionReceipt = {
  receipt_hash: string;
  action_id: string;
  action: string;
  lead_agent: string;
  status: 'written' | 'duplicate' | 'skipped' | 'failed';
  ledger_entry_id: string | null;
  reason: string;
  timestamp: string;
};

function receiptKey(receiptHash: string): string {
  return `agent-ledger-execute:receipt:${receiptHash}`;
}

async function fetchBundle(request: NextRequest, body: LedgerExecuteBody): Promise<ReceiptBundlePayload> {
  const res = await fetch(new URL('/api/agents/receipt-bundle', request.nextUrl.origin), {
    method: 'POST',
    cache: 'no-store',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      action_id: body.action_id,
      operator_ack: body.operator_ack === true,
      receipts: body.receipts ?? {},
    }),
  });
  return (await res.json()) as ReceiptBundlePayload;
}

function mapCategory(action: string): SubstrateEntry['category'] {
  if (action === 'verify' || action === 'attest' || action === 'replay_check') return 'verification';
  if (action === 'stabilize') return 'recommendation';
  if (action === 'escalate') return 'alert';
  return 'observation';
}

function mapSeverity(priority: string): SubstrateEntry['severity'] {
  if (priority === 'critical') return 'critical';
  if (priority === 'high') return 'elevated';
  return 'info';
}

function toSubstrateEntry(bundlePayload: ReceiptBundlePayload): SubstrateEntry {
  const bundle = bundlePayload.bundle!;
  const preview = bundlePayload.ledger_preview;

  return {
    id: `agent-action-${bundle.receipt_hash}`,
    agent: bundle.lead_agent,
    agentOrigin: bundle.lead_agent,
    cycle: bundle.action_id.match(/C-\d+/)?.[0] ?? 'C-297',
    title: preview?.title ?? `Agent action receipt · ${bundle.action}`,
    summary: preview?.summary ?? `Quorum-gated ${bundle.action} action receipt generated by ${bundle.lead_agent}`,
    category: mapCategory(bundle.action),
    severity: mapSeverity(bundle.priority),
    source: 'agent-journal',
    confidence: bundle.executable ? 0.9 : 0.5,
    derivedFrom: [bundle.action_id, bundle.payload_hash, bundle.quorum_hash],
    tags: Array.from(new Set([...(preview?.tags ?? []), 'c297-phase9', 'controlled-ledger-write', `receipt:${bundle.receipt_hash}`, `quorum:${bundle.quorum_hash}`])),
    verified: bundle.executable,
    attestation_signature: {
      kind: 'agent_action_receipt_bundle',
      action_id: bundle.action_id,
      action: bundle.action,
      lead_agent: bundle.lead_agent,
      supporting_agents: bundle.supporting_agents,
      payload_hash: bundle.payload_hash,
      quorum_hash: bundle.quorum_hash,
      receipt_hash: bundle.receipt_hash,
      created_at: bundle.created_at,
    },
  };
}

export async function POST(request: NextRequest) {
  const authError = getServiceAuthError(request);
  const operator = await getOperatorSession();
  if (authError && !operator) return authError;

  let body: LedgerExecuteBody = {};
  try {
    body = (await request.json()) as LedgerExecuteBody;
  } catch {
    body = {};
  }

  const dryRun = body.dry_run !== false;
  const bundlePayload = await fetchBundle(request, body);
  const bundle = bundlePayload.bundle;

  if (!bundlePayload.ok || !bundle) {
    return NextResponse.json(
      {
        ok: false,
        executed: false,
        error: 'receipt_bundle_unavailable',
        bundlePayload,
        timestamp: new Date().toISOString(),
      },
      { status: 200, headers: { 'Cache-Control': 'private, no-store, max-age=0, must-revalidate' } },
    );
  }

  const existing = await kvGet<LedgerExecutionReceipt>(receiptKey(bundle.receipt_hash));
  if (existing) {
    return NextResponse.json(
      {
        ok: true,
        executed: false,
        duplicate: true,
        receipt: { ...existing, status: 'duplicate', reason: 'receipt_hash_already_written' },
        timestamp: new Date().toISOString(),
      },
      { headers: { 'Cache-Control': 'private, no-store, max-age=0, must-revalidate' } },
    );
  }

  if (!bundle.executable) {
    return NextResponse.json(
      {
        ok: true,
        executed: false,
        skipped: true,
        reason: 'bundle_not_executable',
        blocked_by: bundlePayload.blocked_by ?? [],
        bundle,
        timestamp: new Date().toISOString(),
      },
      { headers: { 'Cache-Control': 'private, no-store, max-age=0, must-revalidate' } },
    );
  }

  const entry = toSubstrateEntry(bundlePayload);

  if (dryRun) {
    return NextResponse.json(
      {
        ok: true,
        executed: false,
        dry_run: true,
        would_write: entry,
        bundle,
        canon_law: [
          'Dry-run returns the exact SubstrateEntry that would be sent to the ledger.',
          'Set dry_run=false only after operator review and complete receipts.',
        ],
        timestamp: new Date().toISOString(),
      },
      { headers: { 'Cache-Control': 'private, no-store, max-age=0, must-revalidate' } },
    );
  }

  const write = await writeToSubstrate(entry);
  const receipt: LedgerExecutionReceipt = {
    receipt_hash: bundle.receipt_hash,
    action_id: bundle.action_id,
    action: bundle.action,
    lead_agent: bundle.lead_agent,
    status: write.ok ? 'written' : 'failed',
    ledger_entry_id: write.entryId ?? null,
    reason: write.ok ? 'agent_action_receipt_written_to_ledger' : (write.error ?? 'ledger_write_failed'),
    timestamp: new Date().toISOString(),
  };

  if (write.ok) await kvSet(receiptKey(bundle.receipt_hash), receipt, RECEIPT_WRITE_TTL_SECONDS);

  return NextResponse.json(
    {
      ok: write.ok,
      executed: write.ok,
      receipt,
      bundle,
      ledger_entry: entry,
      canon_law: [
        'This endpoint only writes agent action receipt attestations to Ledger.',
        'It does not mutate Vault, Canon, Replay, MIC, Fountain, or GI.',
        'Receipt hash dedupe prevents duplicate execution records.',
      ],
      timestamp: new Date().toISOString(),
    },
    {
      status: 200,
      headers: {
        'Cache-Control': 'private, no-store, max-age=0, must-revalidate',
        'X-Mobius-Source': 'agent-ledger-execute',
      },
    },
  );
}

export async function GET() {
  return NextResponse.json(
    {
      ok: true,
      version: 'C-297.phase9.controlled-ledger-write.v1',
      usage: {
        method: 'POST',
        body: {
          action_id: 'action-verify-ZEUS',
          operator_ack: true,
          dry_run: true,
          receipts: {
            agent_signature: 'sig-preview',
            verification_verdict: 'valid',
            input_hash: 'hash-preview',
            timestamp: new Date().toISOString(),
          },
        },
      },
      safety: [
        'dry_run defaults to true',
        'requires executable receipt bundle',
        'dedupes by receipt_hash',
        'does not mutate Vault, Canon, Replay, MIC, Fountain, or GI',
      ],
      timestamp: new Date().toISOString(),
    },
    { headers: { 'Cache-Control': 'private, no-store, max-age=0, must-revalidate' } },
  );
}
