import type {
  Agent,
  Attestation,
  CivicRadarAlert,
  EpiconItem,
  GISnapshot,
  LedgerEntry,
  MFSShard,
  Sentinel,
  Tripwire,
} from './types';

export const navItems = [
  { key: 'pulse' as const, label: 'Pulse' },
  { key: 'agents' as const, label: 'Agents' },
  { key: 'ledger' as const, label: 'Ledger' },
  { key: 'wallet' as const, label: 'Wallet' },
  { key: 'markets' as const, label: 'Markets' },
  { key: 'geopolitics' as const, label: 'Geopolitics', badge: 3 },
  { key: 'governance' as const, label: 'Governance' },
  { key: 'reflections' as const, label: 'Reflections' },
  { key: 'infrastructure' as const, label: 'Infrastructure' },
  { key: 'search' as const, label: 'Search' },
  { key: 'settings' as const, label: 'Settings' },
];

export const mockAgents: Agent[] = [
  {
    id: 'atlas',
    name: 'ATLAS',
    role: 'Sentinel / Monitoring',
    color: 'bg-sky-500',
    status: 'analyzing',
    heartbeatOk: true,
    lastAction: 'Scanning substrate integrity',
  },
  {
    id: 'zeus',
    name: 'ZEUS',
    role: 'Verification Engine',
    color: 'bg-amber-500',
    status: 'verifying',
    heartbeatOk: true,
    lastAction: 'Cross-checking source chain',
  },
  {
    id: 'hermes',
    name: 'HERMES',
    role: 'Routing / Signal Flow',
    color: 'bg-rose-500',
    status: 'routing',
    heartbeatOk: true,
    lastAction: 'Routing geopolitical signal',
  },
  {
    id: 'echo',
    name: 'ECHO',
    role: 'Memory / Ledger Intake',
    color: 'bg-slate-400',
    status: 'listening',
    heartbeatOk: true,
    lastAction: 'Recording EPICON snapshot',
  },
  {
    id: 'aurea',
    name: 'AUREA',
    role: 'Architect / Strategy',
    color: 'bg-orange-500',
    status: 'analyzing',
    heartbeatOk: true,
    lastAction: 'Drafting civic synthesis',
  },
  {
    id: 'jade',
    name: 'JADE',
    role: 'Annotation / Morale',
    color: 'bg-emerald-500',
    status: 'idle',
    heartbeatOk: true,
    lastAction: 'Awaiting next reflection input',
  },
  {
    id: 'eve',
    name: 'EVE',
    role: 'Observer / Ethics',
    color: 'bg-fuchsia-500',
    status: 'idle',
    heartbeatOk: true,
    lastAction: 'Observing cross-agent output',
  },
  {
    id: 'daedalus',
    name: 'DAEDALUS',
    role: 'Builder / Research',
    color: 'bg-yellow-700',
    status: 'analyzing',
    heartbeatOk: true,
    lastAction: 'Compiling terminal module sketch',
  },
];

export const mockEpicon: EpiconItem[] = [
  {
    id: 'EPICON-C250-004',
    title: 'Regional escalation signal updated',
    category: 'geopolitical',
    status: 'verified',
    confidenceTier: 3,
    ownerAgent: 'ZEUS',
    timestamp: '2026-03-15 07:41 ET',
    sources: ['Reuters', 'AP', 'Official advisory'],
    summary:
      'Signal upgraded after multi-source verification. Event remains active but below alliance-trigger threshold.',
    trace: [
      'ECHO captured initial signal',
      'HERMES routed for verification',
      'ZEUS confirmed with 3 source alignment',
      'ATLAS updated system integrity context',
    ],
  },
  {
    id: 'EPICON-C250-003',
    title: 'Mobius Terminal V1 layout drafted',
    category: 'governance',
    status: 'verified',
    confidenceTier: 4,
    ownerAgent: 'AUREA',
    timestamp: '2026-03-15 07:28 ET',
    sources: ['Internal design memo'],
    summary:
      'Initial civic terminal layout finalized for operator view with command canvas, right inspector, and agent cortex.',
    trace: [
      'AUREA created layout model',
      'DAEDALUS prepared implementation notes',
      'ECHO archived design record',
    ],
  },
  {
    id: 'EPICON-C250-002',
    title: 'Tripwire divergence on conflict narratives',
    category: 'infrastructure',
    status: 'pending',
    confidenceTier: 2,
    ownerAgent: 'ATLAS',
    timestamp: '2026-03-15 07:16 ET',
    sources: ['Open web', 'Regional reporting'],
    summary:
      'Narrative velocity exceeded verification speed. System placed event into caution state pending source reconciliation.',
    trace: [
      'ATLAS flagged divergence',
      'ZEUS opened verification lane',
      'HERMES throttled propagation',
    ],
  },
  {
    id: 'EPICON-C250-001',
    title: 'Market sweep awaiting fresh inputs',
    category: 'market',
    status: 'contradicted',
    confidenceTier: 1,
    ownerAgent: 'HERMES',
    timestamp: '2026-03-15 06:58 ET',
    sources: ['Secondary feed'],
    summary:
      'Pre-open market interpretation was rejected after source inconsistency. Feed requires refresh before publication.',
    trace: [
      'HERMES routed market signal',
      'ZEUS found inconsistency',
      'ATLAS suppressed downstream amplification',
    ],
  },
];

export const mockTripwires: Tripwire[] = [
  {
    id: 'TW-114',
    label: 'Information Surge',
    severity: 'medium',
    owner: 'ATLAS',
    openedAt: '07:16 ET',
    action: 'Throttled propagation pending ZEUS review',
  },
  {
    id: 'TW-115',
    label: 'Source Divergence',
    severity: 'high',
    owner: 'ZEUS',
    openedAt: '07:21 ET',
    action: 'Awaiting primary-source confirmation',
  },
];

export const mockGI: GISnapshot = {
  score: 0.94,
  delta: 0.01,
  institutionalTrust: 0.88,
  infoReliability: 0.91,
  consensusStability: 0.86,
  weekly: [0.89, 0.9, 0.9, 0.92, 0.91, 0.93, 0.94],
};

// ── Mobius-Substrate: Ledger entries ─────────────────────────

export const mockLedger: LedgerEntry[] = [
  {
    id: 'LE-C250-012',
    cycleId: 'C-250',
    type: 'epicon',
    agentOrigin: 'ECHO',
    timestamp: '2026-03-15 07:41 ET',
    summary: 'EPICON-C250-004 committed — regional escalation signal verified by ZEUS',
    integrityDelta: 0.02,
    status: 'committed',
  },
  {
    id: 'LE-C250-011',
    cycleId: 'C-250',
    type: 'attestation',
    agentOrigin: 'EVE',
    timestamp: '2026-03-15 07:35 ET',
    summary: 'Ethics attestation minted for ATLAS conflict-narrative handling',
    integrityDelta: 0.01,
    status: 'committed',
  },
  {
    id: 'LE-C250-010',
    cycleId: 'C-250',
    type: 'shard',
    agentOrigin: 'JADE',
    timestamp: '2026-03-15 07:28 ET',
    summary: 'MFS-7721 learning shard created — civic terminal design comprehension',
    integrityDelta: 0.005,
    status: 'committed',
  },
  {
    id: 'LE-C250-009',
    cycleId: 'C-250',
    type: 'epicon',
    agentOrigin: 'ECHO',
    timestamp: '2026-03-15 07:16 ET',
    summary: 'EPICON-C250-002 logged — tripwire divergence pending reconciliation',
    integrityDelta: -0.01,
    status: 'pending',
  },
  {
    id: 'LE-C250-008',
    cycleId: 'C-250',
    type: 'settlement',
    agentOrigin: 'HERMES',
    timestamp: '2026-03-15 07:10 ET',
    summary: 'MIC settlement batch dispatched — 14 citizen payouts processed',
    integrityDelta: 0.0,
    status: 'committed',
  },
  {
    id: 'LE-C250-007',
    cycleId: 'C-250',
    type: 'ubi',
    agentOrigin: 'DAEDALUS',
    timestamp: '2026-03-15 06:58 ET',
    summary: 'UBI distribution preview — 342 eligible citizens, 12,400 MIC allocated',
    integrityDelta: 0.0,
    status: 'committed',
  },
  {
    id: 'LE-C250-006',
    cycleId: 'C-250',
    type: 'epicon',
    agentOrigin: 'ECHO',
    timestamp: '2026-03-15 06:58 ET',
    summary: 'EPICON-C250-001 reverted — market sweep contradicted by ZEUS',
    integrityDelta: -0.015,
    status: 'reverted',
  },
];

// ── Mobius-Substrate: MFS Shards ─────────────────────────────

export const mockShards: MFSShard[] = [
  {
    id: 'MFS-7721',
    citizenId: 'CZ-1042',
    archetype: 'learning',
    weight: 0.85,
    qualityScore: 0.92,
    integrityCoefficient: 0.88,
    miiDelta: 0.012,
    timestamp: '2026-03-15 07:28 ET',
  },
  {
    id: 'MFS-7720',
    citizenId: 'CZ-0891',
    archetype: 'verification',
    weight: 0.95,
    qualityScore: 0.97,
    integrityCoefficient: 0.94,
    miiDelta: 0.018,
    timestamp: '2026-03-15 07:22 ET',
  },
  {
    id: 'MFS-7719',
    citizenId: 'CZ-1042',
    archetype: 'governance',
    weight: 0.72,
    qualityScore: 0.81,
    integrityCoefficient: 0.79,
    miiDelta: 0.008,
    timestamp: '2026-03-15 07:15 ET',
  },
];

// ── Mobius-Substrate: Attestations ───────────────────────────

export const mockAttestations: Attestation[] = [
  {
    id: 'ATT-449',
    citizenId: 'CZ-1042',
    type: 'mint',
    reason: 'Consistent verification accuracy over 7 cycles',
    miiImpact: 0.03,
    validatorAgent: 'EVE',
    timestamp: '2026-03-15 07:35 ET',
  },
  {
    id: 'ATT-448',
    citizenId: 'CZ-0891',
    type: 'mint',
    reason: 'Source chain contribution to EPICON-C250-004',
    miiImpact: 0.02,
    validatorAgent: 'ZEUS',
    timestamp: '2026-03-15 07:20 ET',
  },
];

// ── Mobius-Substrate: Sentinel Council ───────────────────────

export const mockSentinels: Sentinel[] = [
  {
    id: 'sentinel-atlas',
    name: 'ATLAS',
    role: 'System Integrity Monitor',
    status: 'active',
    integrity: 0.97,
    provider: 'anthropic',
    lastAction: 'Scanning substrate for coherence fractures',
    domains: ['integrity', 'monitoring', 'escalation'],
  },
  {
    id: 'sentinel-zeus',
    name: 'ZEUS',
    role: 'Verification Arbiter',
    status: 'consensus',
    integrity: 0.96,
    provider: 'openai',
    lastAction: 'Cross-provider verification on EPICON-C250-004',
    domains: ['verification', 'source-chain', 'confidence'],
  },
  {
    id: 'sentinel-eve',
    name: 'EVE',
    role: 'Ethics Observer',
    status: 'active',
    integrity: 0.98,
    provider: 'anthropic',
    lastAction: 'Monitoring agent output for bias patterns',
    domains: ['ethics', 'bias', 'governance'],
  },
  {
    id: 'sentinel-hermes',
    name: 'HERMES',
    role: 'Signal Router',
    status: 'active',
    integrity: 0.95,
    provider: 'google',
    lastAction: 'Routing geopolitical signals to verification lane',
    domains: ['routing', 'prioritization', 'throttling'],
  },
  {
    id: 'sentinel-echo',
    name: 'ECHO',
    role: 'Memory Keeper',
    status: 'active',
    integrity: 0.99,
    provider: 'anthropic',
    lastAction: 'Recording EPICON snapshots to immutable ledger',
    domains: ['memory', 'archival', 'ledger'],
  },
  {
    id: 'sentinel-aurea',
    name: 'AUREA',
    role: 'Strategic Architect',
    status: 'standby',
    integrity: 0.94,
    provider: 'openai',
    lastAction: 'Awaiting next synthesis cycle',
    domains: ['strategy', 'synthesis', 'architecture'],
  },
  {
    id: 'sentinel-jade',
    name: 'JADE',
    role: 'Pattern Analyst',
    status: 'active',
    integrity: 0.93,
    provider: 'google',
    lastAction: 'Analyzing citizen learning patterns for MFS weighting',
    domains: ['annotation', 'patterns', 'morale'],
  },
  {
    id: 'sentinel-daedalus',
    name: 'DAEDALUS',
    role: 'Builder / Researcher',
    status: 'active',
    integrity: 0.92,
    provider: 'meta',
    lastAction: 'Compiling UBI distribution preview for C-250',
    domains: ['research', 'building', 'ubi'],
  },
  {
    id: 'sentinel-uriel',
    name: 'URIEL',
    role: 'Safety Guardian',
    status: 'standby',
    integrity: 0.99,
    provider: 'anthropic',
    lastAction: 'Monitoring escalation paths — no active triggers',
    domains: ['safety', 'escalation', 'veto'],
  },
  {
    id: 'sentinel-zenith',
    name: 'ZENITH',
    role: 'Consensus Coordinator',
    status: 'consensus',
    integrity: 0.96,
    provider: 'google',
    lastAction: 'Coordinating 3-of-10 quorum for attestation batch',
    domains: ['consensus', 'quorum', 'coordination'],
  },
];

// ── Browser Shell: Civic Radar Alerts ────────────────────────

export const mockCivicAlerts: CivicRadarAlert[] = [
  {
    id: 'CRA-2049',
    title: 'Coordinated narrative amplification detected in regional feeds',
    severity: 'high',
    category: 'misinformation',
    source: 'ECHO Threat Intelligence',
    timestamp: '2026-03-15 07:38 ET',
    impact: 'Synthetic amplification pattern across 3 regional news aggregators',
    actions: [
      'ATLAS flagged for downstream monitoring',
      'HERMES throttled propagation velocity',
      'ZEUS opened multi-source verification lane',
    ],
  },
  {
    id: 'CRA-2048',
    title: 'Privacy boundary violation in citizen data pipeline',
    severity: 'critical',
    category: 'privacy',
    source: 'Citizen Shield',
    timestamp: '2026-03-15 07:25 ET',
    impact: 'Unauthorized PII exposure detected in third-party aggregation layer',
    actions: [
      'EVE initiated ethics review',
      'URIEL safety protocol engaged',
      'Pipeline quarantined pending audit',
    ],
  },
  {
    id: 'CRA-2047',
    title: 'Governance proposal sentiment manipulation',
    severity: 'medium',
    category: 'manipulation',
    source: 'HIVE Monitor',
    timestamp: '2026-03-15 07:12 ET',
    impact: 'Astroturfing pattern detected in HIVE governance vote #247',
    actions: [
      'JADE flagged anomalous sentiment patterns',
      'Vote integrity audit initiated',
      'Citizen notification queued',
    ],
  },
  {
    id: 'CRA-2046',
    title: 'MCP server certificate expiration warning',
    severity: 'low',
    category: 'infrastructure',
    source: 'ATLAS Infrastructure Monitor',
    timestamp: '2026-03-15 06:55 ET',
    impact: 'Zeus MCP server TLS certificate expires in 72 hours',
    actions: [
      'DAEDALUS scheduled renewal task',
      'Monitoring interval increased to 1h',
    ],
  },
];
