export type AgentStatus =
  | 'idle'
  | 'listening'
  | 'verifying'
  | 'routing'
  | 'analyzing'
  | 'alert';

export type Agent = {
  id: string;
  name: string;
  role: string;
  color: string;
  status: AgentStatus;
  heartbeatOk: boolean;
  lastAction: string;
};

export type EpiconStatus = 'verified' | 'pending' | 'contradicted';

export type EpiconItem = {
  id: string;
  title: string;
  category:
    | 'geopolitical'
    | 'market'
    | 'governance'
    | 'infrastructure'
    | 'narrative'
    | 'ethics'
    | 'civic-risk';
  status: EpiconStatus;
  confidenceTier: 0 | 1 | 2 | 3 | 4;
  ownerAgent: string;
  sources: string[];
  timestamp: string;
  summary: string;
  trace: string[];
  /** Present on feed entries (e.g. EVE synthesis pipeline) */
  feedSource?: string;
  /** Ledger author lane when present (e.g. EVE governance synthesis) */
  agentOrigin?: string;
  promotionState?: 'pending' | 'selected' | 'promoted' | 'failed';
  assignedAgents?: string[];
  committedEntries?: string[];
  /** ECHO pipeline: original external source + metadata for globe / inspectors */
  echoIngest?: {
    source: string;
    severity: 'low' | 'medium' | 'high';
    metadata?: Record<string, unknown>;
  };
};

export type TripwireLayer =
  | 'information'
  | 'market'
  | 'infrastructure'
  | 'governance'
  | 'cognitive'
  | 'system';

export type TripwireCategory =
  | 'narrative-distortion'
  | 'source-credibility'
  | 'volatility-spike'
  | 'cross-asset-contagion'
  | 'supply-chain'
  | 'institutional-trust'
  | 'echo-chamber'
  | 'amplification'
  | 'agent-drift'
  | 'integrity-drop';

export type Tripwire = {
  id: string;
  label: string;
  severity: 'low' | 'medium' | 'high';
  owner: string;
  openedAt: string;
  action: string;
  /** Detection layer (auto-detected tripwires only) */
  layer?: TripwireLayer;
  /** Detection category (auto-detected tripwires only) */
  category?: TripwireCategory;
  /** Whether this was generated by the detection engine */
  autoDetected?: boolean;
  /** Metric name that triggered detection */
  triggerMetric?: string;
  /** Threshold value that was exceeded */
  triggerThreshold?: number;
  /** Actual value that triggered the tripwire */
  triggerValue?: number;
  /** Related EPICON IDs */
  relatedEpicons?: string[];
};

export type GISnapshot = {
  score: number;
  delta: number;
  mode?: 'green' | 'yellow' | 'red';
  terminalStatus?: 'nominal' | 'stressed' | 'critical';
  primaryDriver?: string;
  summary?: string;
  institutionalTrust: number;
  infoReliability: number;
  consensusStability: number;
  signalBreakdown?: {
    quality: number;
    freshness: number;
    stability: number;
    system: number;
  };
  weekly: number[];
};

export type NavKey =
  | 'globe'
  | 'pulse'
  | 'agents'
  | 'ledger'
  | 'wallet'
  | 'markets'
  | 'geopolitics'
  | 'governance'
  | 'reflections'
  | 'infrastructure'
  | 'sentiment'
  | 'search'
  | 'settings';

export type CommandResult = {
  ok: boolean;
  message: string;
};

// ── Mobius-Substrate types ────────────────────────────────────

export type LedgerCycleAlignment = 'attested' | 'inferred' | 'unknown';

export type LedgerEntry = {
  id: string;
  cycleId: string;
  /** Whether cycleId came from source metadata, safe inference, or remains unknown. */
  cycleAlignment?: LedgerCycleAlignment;
  /** Human-readable source for cycle alignment decisions. */
  cycleAlignmentReason?: string;
  type: 'epicon' | 'attestation' | 'shard' | 'ubi' | 'settlement';
  agentOrigin: string;
  timestamp: string;
  title?: string;
  summary: string;
  integrityDelta: number;
  status: 'committed' | 'pending' | 'reverted';
  /** Human-readable reason explaining why the current proof status was assigned. */
  statusReason?: string;
  /** Evidence source used for status assignment, e.g. github_merge, epicon_verified, feed_status. */
  proofSource?: string;
  /** Canon lifecycle state. Pending rows can still be visible without being sealed. */
  canonState?: 'hot' | 'candidate' | 'attested' | 'sealed' | 'blocked';
  category?:
    | 'geopolitical'
    | 'market'
    | 'governance'
    | 'infrastructure'
    | 'narrative'
    | 'ethics'
    | 'civic-risk';
  confidenceTier?: number;
  tags?: string[];
  source?: 'mock' | 'echo' | 'backfill' | 'eve-synthesis' | 'agent_commit';
};

export type AgentJournalStatus = 'draft' | 'committed' | 'contested' | 'verified';
export type AgentJournalCategory = 'observation' | 'inference' | 'alert' | 'recommendation' | 'close';
export type AgentJournalSeverity = 'nominal' | 'elevated' | 'critical';

export interface AgentJournalEntry {
  id: string;
  agent: string;
  cycle: string;
  timestamp: string;
  scope: string;
  observation: string;
  inference: string;
  recommendation: string;
  confidence: number;
  derivedFrom: string[];
  relatedAgents: string[];
  status: AgentJournalStatus;
  contestedBy?: string[];
  verifiedBy?: string;
  category: AgentJournalCategory;
  severity: AgentJournalSeverity;
  source: 'agent-journal';
  agentOrigin: string;
  tags?: string[];
}

export type MFSShard = {
  id: string;
  citizenId: string;
  archetype: 'learning' | 'verification' | 'governance' | 'creation' | 'reflection' | 'protection' | 'connection';
  weight: number;
  qualityScore: number;
  integrityCoefficient: number;
  miiDelta: number;
  timestamp: string;
};

export type Attestation = {
  id: string;
  citizenId: string;
  type: 'mint' | 'burn';
  reason: string;
  miiImpact: number;
  validatorAgent: string;
  timestamp: string;
};

export type Sentinel = {
  id: string;
  name: string;
  role: string;
  status: 'active' | 'standby' | 'consensus' | 'veto';
  integrity: number;
  provider: string;
  lastAction: string;
  domains: string[];
};

// ── Browser Shell types ──────────────────────────────────────

export type CivicAlertSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

export type CivicRadarAlert = {
  id: string;
  title: string;
  severity: CivicAlertSeverity;
  category: 'misinformation' | 'privacy' | 'manipulation' | 'infrastructure' | 'governance';
  source: string;
  timestamp: string;
  impact: string;
  actions: string[];
};

export type InspectorTarget =
  | { kind: 'epicon'; data: EpiconItem }
  | { kind: 'agent'; data: Agent }
  | { kind: 'tripwire'; data: Tripwire }
  | { kind: 'gi'; data: GISnapshot }
  | { kind: 'ledger'; data: LedgerEntry }
  | { kind: 'shard'; data: MFSShard }
  | { kind: 'alert'; data: CivicRadarAlert }
  | { kind: 'sentinel'; data: Sentinel }
  | { kind: 'signal'; data: SignalScoreTarget };

/** Signal Engine score data for inspector display */
export type SignalScoreTarget = {
  eventId: string;
  title: string;
  category: EpiconItem['category'];
  signal: number;
  narrative: number;
  volatility: number;
  classification: string;
  divergence: number;
  summary: string;
};
